CREATE OR REPLACE TRIGGER TRG_INSERT_ORM_USER
BEFORE INSERT ON ORM_USER
FOR EACH ROW
BEGIN
  :NEW.user_id:=ORM_USER_ID.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_INSERT_ORM_GROUP
BEFORE INSERT ON ORM_GROUP
FOR EACH ROW
BEGIN
  :NEW.group_id:=ORM_GROUP_ID.NEXTVAL;
END;