CREATE TABLE ORMACCOUNT
(
	account_login VARCHAR(50) NOT NULL,
	account_password VARCHAR(50) NOT NULL,
	account_status VARCHAR(100) NOT NULL,
	account_date_reg DATE NOT NULL
);

CREATE TABLE ORMEVENT
(
	event_id INTEGER NOT NULL,
	priority_value INTEGER NOT NULL,
	account_login VARCHAR(50) NOT NULL,
	event_date DATETIME NULL,
	event_description VARCHAR(100) NULL,
	event_state SMALLINT NOT NULL,
);

CREATE TABLE ORMPRIORITY
(
	priority_value INTEGER NOT NULL,
	priority_description VARCHAR(50) NOT NULL
);

ALTER TABLE ORMACCOUNT ADD CONSTRAINT ORMACCOUNT_PK PRIMARY KEY (account_login);
ALTER TABLE ORMEVENT ADD CONSTRAINT ORMEVENT_PK PRIMARY KEY (event_id);
ALTER TABLE ORMPRIORITY ADD CONSTRAINT ORMPRIORITY_PK PRIMARY KEY (priority_value);

ALTER TABLE ORMEVENT ADD CONSTRAINT ORMEVENTPRIORITY_FK FOREIGN KEY (priority_value) REFERENCES ORMPRIORITY(priority_value);
ALTER TABLE ORMEVENT ADD CONSTRAINT ORMEVENTACCOUNT_FK FOREIGN KEY (account_login) REFERENCES ORMACCOUNT(account_login);