CREATE OR REPLACE TRIGGER TRG_INSERT_ORM_USER
BEFORE INSERT ON ORM_USER_NAME
FOR EACH ROW
BEGIN
  :NEW.user_id:=orm_user_id.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER TRG_INSERT_ORM_NETWORK
BEFORE INSERT ON ORM_NETWORK_NAME
FOR EACH ROW
BEGIN
  :NEW.network_id:=orm_network_id.NEXTVAL;
END;